# ============================================
#                 DEV
# ============================================
FROM gradle:8.7-jdk21 AS dev
WORKDIR /app

# Copier uniquement les fichiers de build pour maximiser le cache image
COPY build.gradle* settings.gradle* gradle.properties* ./
COPY gradle ./gradle

# Expose pour Spring Boot dev
EXPOSE 8100

# Lancer Spring Boot en mode dev
CMD ["gradle", "bootRun", "--no-daemon"]
