package com.auth.domain.errors;

/**
 * Codes d'erreur métier alignés sur les agrégats du domaine (credentials, sessions, MFA, tokens).
 */
public enum CodesError {

	// Communs
	PUBLIC_ID_INVALID,
	USER_ID_INVALID,

	// Politiques métier / sécurité
	ACCESS_DENIED,
	SESSIONS_LIMIT_EXCEEDED,
	MFA_MANDATORY_NOT_ENROLLED,

	// Credential
	CREDENTIALS_EMAIL_INVALID,
	CREDENTIALS_PASSWORD_INVALID,
	CREDENTIALS_PUBLIC_ID_INVALID,
	CREDENTIALS_USER_ID_INVALID,
	CREDENTIALS_NOT_FOUND,
	CREDENTIALS_INACTIVE,

	// Session
	SESSIONS_PUBLIC_ID_INVALID,
	SESSIONS_USER_ID_INVALID,
	SESSIONS_IP_ADDRESS_INVALID,
	SESSIONS_USER_AGENT_INVALID,
	SESSIONS_REFRESH_TOKEN_INVALID,
	SESSIONS_DEVICE_NAME_INVALID,
	SESSIONS_EXPIRES_AT_INVALID,
	SESSIONS_NOT_FOUND,
	SESSIONS_EXPIRED,
	SESSIONS_REVOKED,

	// MfaDevice
	MFA_DEVICES_PUBLIC_ID_INVALID,
	MFA_DEVICES_USER_ID_INVALID,
	MFA_DEVICES_TYPE_INVALID,
	MFA_DEVICES_SECRET_INVALID,
	MFA_DEVICES_PHONE_INVALID,
	MFA_DEVICES_DEVICE_NAME_INVALID,
	MFA_DEVICES_NOT_FOUND,
	MFA_DEVICES_INACTIVE,

	// Token
	TOKENS_PUBLIC_ID_INVALID,
	TOKENS_TYPE_INVALID,
	TOKENS_VALUE_INVALID,
	TOKENS_EXPIRES_AT_INVALID,
	TOKENS_NOT_FOUND,
	TOKENS_EXPIRED,
}
